
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ibrahim
 */
public class restaurantReviewPanel2 extends javax.swing.JPanel {

    /**
     * Creates new form restaurantReviewJPanel
     */
    public restaurantReviewPanel2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reviewArea = new javax.swing.JEditorPane();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(128, 128, 128)));
        setPreferredSize(new java.awt.Dimension(360, 100));
        setLayout(new java.awt.BorderLayout());

        reviewArea.setContentType("text/html"); // NOI18N
        reviewArea.setText("");
        reviewArea.setPreferredSize(new java.awt.Dimension(360, 138));
        add(reviewArea, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    
    public void setContent(String customerName,String review,String date, String rate){
        
        String htlmlStr="";
        
        File f=new File("src/reviewHtml.html");
        
        FileInputStream fis=null;
        try {
            fis=new FileInputStream(f);
            int r;
            while((r=fis.read())!=-1){
                htlmlStr+=(char)r;
            }
                fis.close();
                
                String formattedReview="";
                int len=review.length();
                
                for (int i = 0; i < len; i+=50) {
                    if (len-(i+40)<0) {
                        formattedReview+=review.substring(i,len);
                        break;
                    }
                    formattedReview+=review.substring(i,i+40)+"<br>";
            }
                System.out.println(formattedReview);
                htlmlStr=String.format(htlmlStr,customerName,date,rate,
                        formattedReview);
                
                reviewArea.setText(htlmlStr);
                
        } catch (IOException ex) {
            Logger.getLogger(window.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane reviewArea;
    // End of variables declaration//GEN-END:variables
}
