
import customscrollbar.customScrollBarUI;
import connectdb.ConnectDB;
import java.awt.Color;
import java.awt.Component;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ibrahim
 */
public class window extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    ConnectDB appDB;
    public window() {
        appDB=new ConnectDB();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rootPanel = new javax.swing.JPanel();
        windowSplitPane = new javax.swing.JSplitPane();
        userPanel = new javax.swing.JPanel();
        AppNameLabel2 = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        settingsButton = new javax.swing.JButton();
        CardPanel = new javax.swing.JPanel();
        commerceWindowPanel = new javax.swing.JPanel();
        marketsTopPanel = new javax.swing.JPanel();
        restaurantsLabel = new javax.swing.JLabel();
        marketsScrollPane = new javax.swing.JScrollPane();
        marketsPlace = new javax.swing.JPanel();
        loginPanel = new javax.swing.JPanel();
        emailField = new javax.swing.JTextField();
        passwdField = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        signUpInformLabel = new javax.swing.JLabel();
        SignUpButton = new javax.swing.JButton();
        AppNameLabel = new javax.swing.JLabel();
        applyLogInButton = new javax.swing.JButton();
        backToMarketScreenButton = new javax.swing.JButton();
        signUpPanel = new javax.swing.JPanel();
        signUpSurNameField = new javax.swing.JTextField();
        signUpEmailField = new javax.swing.JTextField();
        signUpPasswdField = new javax.swing.JPasswordField();
        signUpNameField1 = new javax.swing.JTextField();
        confirmSignUpButton1 = new javax.swing.JButton();
        AppNameLabel1 = new javax.swing.JLabel();
        backToMarketScreenButton1 = new javax.swing.JButton();
        ErrorLabel = new javax.swing.JLabel();
        userSettingsPanel = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        userInfoPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        changeSettingsPanel = new javax.swing.JPanel();
        selectedMarketPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(640, 360));

        rootPanel.setPreferredSize(new java.awt.Dimension(640, 360));
        rootPanel.setLayout(new java.awt.BorderLayout());

        windowSplitPane.setPreferredSize(new java.awt.Dimension(640, 360));

        userPanel.setBackground(new java.awt.Color(255, 0, 0));
        userPanel.setPreferredSize(new java.awt.Dimension(140, 360));

        AppNameLabel2.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        AppNameLabel2.setText("Deliver2Me");

        loginButton.setBackground(new java.awt.Color(254, 254, 254));
        loginButton.setForeground(new java.awt.Color(1, 1, 1));
        loginButton.setText("Login");
        loginButton.setFocusable(false);
        loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginButtonMouseClicked(evt);
            }
        });

        settingsButton.setBackground(new java.awt.Color(254, 254, 254));
        settingsButton.setText("Settings");
        settingsButton.setFocusable(false);
        settingsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingsButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout userPanelLayout = new javax.swing.GroupLayout(userPanel);
        userPanel.setLayout(userPanelLayout);
        userPanelLayout.setHorizontalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AppNameLabel2)
                    .addComponent(settingsButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        userPanelLayout.setVerticalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AppNameLabel2)
                .addGap(18, 18, 18)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(settingsButton)
                .addContainerGap(188, Short.MAX_VALUE))
        );

        windowSplitPane.setLeftComponent(userPanel);

        CardPanel.setBackground(new java.awt.Color(235, 204, 204));
        CardPanel.setPreferredSize(new java.awt.Dimension(500, 360));
        CardPanel.setLayout(new java.awt.CardLayout());

        commerceWindowPanel.setBackground(new java.awt.Color(255, 255, 255));
        commerceWindowPanel.setName("rootPanel"); // NOI18N
        commerceWindowPanel.setPreferredSize(new java.awt.Dimension(500, 360));
        commerceWindowPanel.setLayout(new java.awt.BorderLayout());

        marketsTopPanel.setBackground(new java.awt.Color(240, 240, 240));
        marketsTopPanel.setForeground(new java.awt.Color(1, 1, 1));
        marketsTopPanel.setPreferredSize(new java.awt.Dimension(500, 60));

        restaurantsLabel.setBackground(new java.awt.Color(1, 1, 1));
        restaurantsLabel.setFont(new java.awt.Font("DejaVu Serif", 2, 24)); // NOI18N

        javax.swing.GroupLayout marketsTopPanelLayout = new javax.swing.GroupLayout(marketsTopPanel);
        marketsTopPanel.setLayout(marketsTopPanelLayout);
        marketsTopPanelLayout.setHorizontalGroup(
            marketsTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(marketsTopPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(restaurantsLabel)
                .addContainerGap(425, Short.MAX_VALUE))
        );
        marketsTopPanelLayout.setVerticalGroup(
            marketsTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(marketsTopPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(restaurantsLabel)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        commerceWindowPanel.add(marketsTopPanel, java.awt.BorderLayout.NORTH);

        marketsScrollPane.setBackground(new java.awt.Color(240, 240, 240));
        marketsScrollPane.setPreferredSize(new java.awt.Dimension(500, 360));
        //marketsScrollPane.getViewport().setBackground(new java.awt.Color(255, 96, 32));
        marketsScrollPane.setVerticalScrollBar(new customscrollbar.customScrollBar());

        marketsPlace.setBackground(new java.awt.Color(254, 254, 254));
        marketsPlace.setBorder(javax.swing.BorderFactory.createTitledBorder("Markets"));
        marketsPlace.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        marketsPlace.setPreferredSize(new java.awt.Dimension(500, 360));
        marketsPlace.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                marketsPlaceMouseClicked(evt);
            }
        });
        marketsPlace.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 20));
        marketsScrollPane.setViewportView(marketsPlace);
        //add sample markets to panel for unauthorized users
        addMarketsToScrollPane(appDB.getRestaurantsGUI());

        commerceWindowPanel.add(marketsScrollPane, java.awt.BorderLayout.CENTER);

        CardPanel.add(commerceWindowPanel, "commerceWindowCard");

        loginPanel.setBackground(new java.awt.Color(255, 255, 255));
        loginPanel.setName("loginPanel"); // NOI18N
        loginPanel.setPreferredSize(new java.awt.Dimension(500, 360));

        emailField.setForeground(new java.awt.Color(34, 34, 34));
        emailField.setText("Enter email");
        emailField.setToolTipText("Example: halilibo@mail.com");
        emailField.setName("emailField"); // NOI18N
        emailField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFieldFocusLost(evt);
            }
        });

        passwdField.setText("Enter password");
        passwdField.setToolTipText("Example: ibo123");
        passwdField.setEchoChar((char)0);
        passwdField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwdFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwdFieldFocusLost(evt);
            }
        });

        signUpInformLabel.setText("Do not have an account?");

        SignUpButton.setBackground(new java.awt.Color(254, 254, 254));
        SignUpButton.setText("Sign up");
        SignUpButton.setFocusable(false);
        SignUpButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignUpButtonMouseClicked(evt);
            }
        });

        AppNameLabel.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        AppNameLabel.setText("Deliver2Me");

        applyLogInButton.setBackground(new java.awt.Color(254, 254, 254));
        applyLogInButton.setText("Log in");
        applyLogInButton.setFocusable(false);
        applyLogInButton.setMaximumSize(new java.awt.Dimension(74, 35));
        applyLogInButton.setMinimumSize(new java.awt.Dimension(74, 35));
        applyLogInButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                applyLogInButtonMouseClicked(evt);
            }
        });
        applyLogInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyLogInButtonActionPerformed(evt);
            }
        });

        backToMarketScreenButton.setBackground(new java.awt.Color(254, 254, 254));
        backToMarketScreenButton.setText("Back");
        backToMarketScreenButton.setToolTipText("Back to marketplaces");
        backToMarketScreenButton.setFocusable(false);
        backToMarketScreenButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backToMarketScreenButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(loginPanelLayout.createSequentialGroup()
                                .addComponent(signUpInformLabel)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(loginPanelLayout.createSequentialGroup()
                                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator1)
                                    .addComponent(AppNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(emailField)
                                    .addComponent(passwdField, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGap(156, 156, 156)
                                .addComponent(backToMarketScreenButton))))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(applyLogInButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(SignUpButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AppNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backToMarketScreenButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passwdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(applyLogInButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(signUpInformLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SignUpButton)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        CardPanel.add(loginPanel, "loginWindowCard");

        signUpPanel.setBackground(new java.awt.Color(255, 255, 255));
        signUpPanel.setPreferredSize(new java.awt.Dimension(500, 360));

        signUpSurNameField.setForeground(new java.awt.Color(34, 34, 34));
        signUpSurNameField.setText("Enter surname");
        signUpSurNameField.setToolTipText("");
        signUpSurNameField.setName("emailField"); // NOI18N
        signUpSurNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                signUpSurNameFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                signUpSurNameFieldFocusLost(evt);
            }
        });

        signUpEmailField.setForeground(new java.awt.Color(34, 34, 34));
        signUpEmailField.setText("Enter email");
        signUpEmailField.setToolTipText("Example: halo@mail.com");
        signUpEmailField.setName("emailField"); // NOI18N
        signUpEmailField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                signUpEmailFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                signUpEmailFieldFocusLost(evt);
            }
        });

        signUpPasswdField.setText("Enter password");
        signUpPasswdField.setToolTipText("Example: ibo123");
        signUpPasswdField.setEchoChar((char)0);
        signUpPasswdField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                signUpPasswdFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                signUpPasswdFieldFocusLost(evt);
            }
        });

        signUpNameField1.setForeground(new java.awt.Color(34, 34, 34));
        signUpNameField1.setText("Enter name");
        signUpNameField1.setToolTipText("");
        signUpNameField1.setName("emailField"); // NOI18N
        signUpNameField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                signUpNameField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                signUpNameField1FocusLost(evt);
            }
        });

        confirmSignUpButton1.setBackground(new java.awt.Color(254, 254, 254));
        confirmSignUpButton1.setText("Confirm and Sign up");
        confirmSignUpButton1.setFocusable(false);
        confirmSignUpButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmSignUpButton1MouseClicked(evt);
            }
        });

        AppNameLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        AppNameLabel1.setText("Deliver2Me");

        backToMarketScreenButton1.setBackground(new java.awt.Color(254, 254, 254));
        backToMarketScreenButton1.setText("Back");
        backToMarketScreenButton1.setToolTipText("Back to marketplaces");
        backToMarketScreenButton1.setFocusable(false);
        backToMarketScreenButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backToMarketScreenButton1MouseClicked(evt);
            }
        });

        ErrorLabel.setBackground(new java.awt.Color(254, 254, 254));
        ErrorLabel.setForeground(new java.awt.Color(0, 0, 0));
        ErrorLabel.setText("Do not leave any field blank!");
        ErrorLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
        ErrorLabel.setVisible(false);

        javax.swing.GroupLayout signUpPanelLayout = new javax.swing.GroupLayout(signUpPanel);
        signUpPanel.setLayout(signUpPanelLayout);
        signUpPanelLayout.setHorizontalGroup(
            signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signUpPanelLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(signUpPasswdField)
                    .addComponent(signUpEmailField)
                    .addComponent(signUpSurNameField)
                    .addComponent(signUpNameField1)
                    .addComponent(AppNameLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signUpPanelLayout.createSequentialGroup()
                        .addComponent(confirmSignUpButton1)
                        .addGap(6, 6, 6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(backToMarketScreenButton1)
                .addContainerGap())
            .addGroup(signUpPanelLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(ErrorLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        signUpPanelLayout.setVerticalGroup(
            signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signUpPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backToMarketScreenButton1)
                    .addComponent(AppNameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(signUpNameField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(signUpSurNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(signUpEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(signUpPasswdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ErrorLabel)
                .addGap(5, 5, 5)
                .addComponent(confirmSignUpButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CardPanel.add(signUpPanel, "signUpWindowCard");

        userSettingsPanel.setBackground(new java.awt.Color(254, 254, 254));
        userSettingsPanel.setPreferredSize(new java.awt.Dimension(500, 360));

        jTabbedPane1.setBackground(new java.awt.Color(201, 201, 201));

        jScrollPane1.setVerticalScrollBar(new customscrollbar.customScrollBar());

        jEditorPane1.setContentType("text/html"); // NOI18N
        jEditorPane1.setText("<html> <style> #lineBorder {   border: 2px solid powderblue; } h1{   list-style-type: none;   margin: 0;   padding: 0;   overflow: hidden;   background-color: #cacaca; }  h2{   list-style-type: none;   margin: 0;   padding: 10px 0px 10px 40px;   overflow: hidden;   background-color: #cacaca; }  ul {   list-style-type: none;   margin: 0;   padding: 10px 0px 10px 40px;   overflow: hidden;   background-color: #f0f0f0; }  </style> <body>  <h1>Settings</h1>   <h2>User</h2> <ul> <li id=LineBorder>name</li> <li id=LineBorder>surname</li> <li id=LineBorder>email</li> </ul>   <h2>Address book</h2> <ul> <li id=LineBorder><pre>city\t\tcityCode</pre></li> <li id=LineBorder>address;</li> <li id=LineBorder>address2;</li> </ul>   <h2>Payment</h2> <ul> <li id=LineBorder>card1</li> <li id=LineBorder>card2</li> <li id=LineBorder>card3</li> </ul>   </body> </html>");
        jEditorPane1.setToolTipText("");
        jScrollPane1.setViewportView(jEditorPane1);

        javax.swing.GroupLayout userInfoPanelLayout = new javax.swing.GroupLayout(userInfoPanel);
        userInfoPanel.setLayout(userInfoPanelLayout);
        userInfoPanelLayout.setHorizontalGroup(
            userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
                .addContainerGap())
        );
        userInfoPanelLayout.setVerticalGroup(
            userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("tab1", userInfoPanel);

        javax.swing.GroupLayout changeSettingsPanelLayout = new javax.swing.GroupLayout(changeSettingsPanel);
        changeSettingsPanel.setLayout(changeSettingsPanelLayout);
        changeSettingsPanelLayout.setHorizontalGroup(
            changeSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 433, Short.MAX_VALUE)
        );
        changeSettingsPanelLayout.setVerticalGroup(
            changeSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 327, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab2", changeSettingsPanel);

        javax.swing.GroupLayout userSettingsPanelLayout = new javax.swing.GroupLayout(userSettingsPanel);
        userSettingsPanel.setLayout(userSettingsPanelLayout);
        userSettingsPanelLayout.setHorizontalGroup(
            userSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        userSettingsPanelLayout.setVerticalGroup(
            userSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        CardPanel.add(userSettingsPanel, "userSettingsCard");

        selectedMarketPanel.setPreferredSize(new java.awt.Dimension(500, 360));
        selectedMarketPanel.setLayout(new java.awt.BorderLayout());
        CardPanel.add(selectedMarketPanel, "selectedMarketCard");

        windowSplitPane.setRightComponent(CardPanel);

        rootPanel.add(windowSplitPane, java.awt.BorderLayout.CENTER);

        getContentPane().add(rootPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFieldFocusGained
        // TODO add your handling code here:
        if ( emailField.getText().equals("Enter email")
                || emailField.getText().equals("email may be wrong!") ){
            emailField.setBackground(Color.white);
            emailField.setForeground(Color.black);
            
            emailField.setText("");
        }
    }//GEN-LAST:event_emailFieldFocusGained

    private void emailFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFieldFocusLost
        // TODO add your handling code here:
        if (emailField.getText().isEmpty() ) {
            emailField.setText( "Enter email" );
        }
    }//GEN-LAST:event_emailFieldFocusLost

    private void passwdFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwdFieldFocusGained
        // TODO add your handling code here:
        if (passwdField.getText().equals("Enter password")
                || passwdField.getText().equals("password may be wrong!")) {
            
            passwdField.setBackground(Color.white);
            passwdField.setForeground(Color.black);
            
            passwdField.setText("");
            passwdField.setEchoChar('*');
        }
    }//GEN-LAST:event_passwdFieldFocusGained

    private void passwdFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwdFieldFocusLost
        // TODO add your handling code here:
        if (passwdField.getText().isEmpty() ) {
            passwdField.setText( "Enter password" );
            passwdField.setEchoChar((char)0);
        }
    }//GEN-LAST:event_passwdFieldFocusLost

    private void SignUpButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUpButtonMouseClicked
        // TODO add your handling code here:
        java.awt.CardLayout c=(java.awt.CardLayout)(CardPanel.getLayout());
        c.show(CardPanel, "signUpWindowCard");
    }//GEN-LAST:event_SignUpButtonMouseClicked

    private void applyLogInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyLogInButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_applyLogInButtonActionPerformed

    private void backToMarketScreenButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backToMarketScreenButtonMouseClicked
        // TODO add your handling code here:
        java.awt.CardLayout c=(java.awt.CardLayout)(CardPanel.getLayout());
        c.show(CardPanel, "commerceWindowCard");
    }//GEN-LAST:event_backToMarketScreenButtonMouseClicked

    private void signUpSurNameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_signUpSurNameFieldFocusGained
        // TODO add your handling code here:
        if (signUpSurNameField.getText().equals("Enter surname")) {
            signUpSurNameField.setText("");
        }
    }//GEN-LAST:event_signUpSurNameFieldFocusGained

    private void signUpSurNameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_signUpSurNameFieldFocusLost
        // TODO add your handling code here:
        if (signUpSurNameField.getText().isEmpty()) {
            signUpSurNameField.setText("Enter surname");
        }
    }//GEN-LAST:event_signUpSurNameFieldFocusLost

    private void signUpEmailFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_signUpEmailFieldFocusGained
        // TODO add your handling code here:
        if (signUpEmailField.getText().equals("Enter email") ) {
            signUpEmailField.setText( "" );
        }
    }//GEN-LAST:event_signUpEmailFieldFocusGained

    private void signUpEmailFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_signUpEmailFieldFocusLost
        // TODO add your handling code here:
        if (signUpEmailField.getText().isEmpty() ) {
            signUpEmailField.setText( "Enter email" );
        }
    }//GEN-LAST:event_signUpEmailFieldFocusLost

    private void signUpPasswdFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_signUpPasswdFieldFocusGained
        // TODO add your handling code here:
        if (signUpPasswdField.getText().equals("Enter password") ) {
            signUpPasswdField.setText("");
            signUpPasswdField.setEchoChar('*');
        }
    }//GEN-LAST:event_signUpPasswdFieldFocusGained

    private void signUpPasswdFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_signUpPasswdFieldFocusLost
        // TODO add your handling code here:
        if (signUpPasswdField.getText().isEmpty() ) {
            signUpPasswdField.setText( "Enter password" );
            signUpPasswdField.setEchoChar((char)0);
        }
    }//GEN-LAST:event_signUpPasswdFieldFocusLost

    private void signUpNameField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_signUpNameField1FocusGained
        // TODO add your handling code here:
        if (signUpNameField1.getText().equals("Enter name")) {
            signUpNameField1.setText("");
        }
    }//GEN-LAST:event_signUpNameField1FocusGained

    private void signUpNameField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_signUpNameField1FocusLost
        // TODO add your handling code here:
        if (signUpNameField1.getText().isEmpty()) {
            signUpNameField1.setText("Enter name");
        }
    }//GEN-LAST:event_signUpNameField1FocusLost

    private void backToMarketScreenButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backToMarketScreenButton1MouseClicked
        // TODO add your handling code here:
        java.awt.CardLayout c=(java.awt.CardLayout)(CardPanel.getLayout());
        c.show(CardPanel, "commerceWindowCard");
    }//GEN-LAST:event_backToMarketScreenButton1MouseClicked

    private void loginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMouseClicked
        // TODO add your handling code here:
        java.awt.CardLayout c=(java.awt.CardLayout)(CardPanel.getLayout());
        c.show(CardPanel, "loginWindowCard");
    }//GEN-LAST:event_loginButtonMouseClicked

    private void applyLogInButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_applyLogInButtonMouseClicked
        // TODO add your handling code here:
        appDB.logIn("halilibo@mail.com","ibo123");
        //appDB.logIn(emailField.getText(), String.valueOf(passwdField.getPassword()) );
        
        //authentication failed
        if (appDB.isLogged()<1) {
            emailField.setBackground(Color.red);
            emailField.setForeground(Color.white);
            passwdField.setBackground(Color.red);
            passwdField.setForeground(Color.white);
            
            emailField.setText("email may be wrong!");
            passwdField.setText("password may be wrong!");
        }else{//auth success
            
            marketsPlace.removeAll();
            
            java.awt.CardLayout c=(java.awt.CardLayout)(CardPanel.getLayout());
            c.show(CardPanel, "commerceWindowCard");
            
            addMarketsToScrollPane(appDB.account.getRestaurantsPopularity());
            
            restaurantsLabel.setText(String.format("Restaurants on %s",appDB.account.getID()[2] ));
            //System.out.println(getClass().getResource("userInfoHtml.html"));
            /*
            Path fileName=Path.of( getClass().getResource("userInfoHtml.html") );
            String html=Files.readAllBytes();
            */
            
        }
    }//GEN-LAST:event_applyLogInButtonMouseClicked

    
    private void confirmSignUpButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmSignUpButton1MouseClicked
        // TODO add your handling code here:
        
        if (signUpNameField1.getText().equals("Enter name")
                || signUpSurNameField.getText().equals("Enter surname")
                || signUpEmailField.getText().equals("Enter email")
                || signUpPasswdField.getText().equals("Enter password")) {
            
            ErrorLabel.setVisible(true);
        }else{
            
            String query="insert into customer(name, surname, email, passwd)"
                    +" values (%s, %s, %s, %s)";
            query=String.format(query,
                    signUpNameField1.getText()
                    ,signUpSurNameField.getText()
                    ,signUpEmailField.getText()
                    ,String.valueOf(signUpPasswdField.getText()) );
            System.out.println(query);
            //appDB.updateDB(query);
            
            /*
            forward to settings to set up its informations
            */
        }
    }//GEN-LAST:event_confirmSignUpButton1MouseClicked

    private void settingsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsButtonMouseClicked
        // TODO add your handling code here:
        java.awt.CardLayout c=(java.awt.CardLayout)(CardPanel.getLayout());
        c.show(CardPanel, "userSettingsCard");
    }//GEN-LAST:event_settingsButtonMouseClicked

    private void marketsPlaceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_marketsPlaceMouseClicked
        // TODO add your handling code here:
        Component[] c=marketsPlace.getComponents();
        java.awt.Point mPos=evt.getPoint();
        
        for(Component cpt:c){
            if (mPos.getX()>=cpt.getX()
                    && mPos.getX()<=cpt.getX()+cpt.getWidth() ) {
                
                if (mPos.getY()>=cpt.getY()
                    && mPos.getY()<=cpt.getY()+cpt.getHeight()) {
                    
                    marketPlaceBox mpb=(marketPlaceBox)cpt;
                    getSelectedMarketPlace(mpb);
                }
   
            }
        }
    }//GEN-LAST:event_marketsPlaceMouseClicked

    private void getSelectedMarketPlace(marketPlaceBox market){
        
        marketDetailBox mDetail=new marketDetailBox();
        javax.swing.JPanel p=(javax.swing.JPanel)market.getComponent(0);
        javax.swing.JLabel label=(javax.swing.JLabel)p.getComponent(1);
        mDetail.setMarketNameLabel(label.getText());
        
        List<List<String>> list;
        if (appDB.isLogged()<1) {
            list=appDB.getMenues(market.getRestaurantID());
            mDetail.appendReview(appDB.getCommentsOfRestaurant(market.getRestaurantID()));
        }else{
            list=appDB.account.getMenues(market.getRestaurantID());
            mDetail.appendReview(appDB.account.getCommentsOfRestaurant(market.getRestaurantID()));
        }
        
        for (int i = 0; i < list.size(); i++) {
            mDetail.appendMenu(list.get(i).get(0), list.get(i).get(1));
        }
        
        
        selectedMarketPanel.removeAll();
        selectedMarketPanel.add(mDetail);
        
        java.awt.CardLayout c=(java.awt.CardLayout)(CardPanel.getLayout());
        c.show(CardPanel, "selectedMarketCard");
        
    }
    
    private void addMarketToScrollPane(int marketID,String marketName,String marketRating){

            marketPlaceBox a=new marketPlaceBox();
            
            a.setPreferredSize(new java.awt.Dimension(192,192));
            
            a.setRestaurantID(marketID);
            a.setNameLabel(marketName);
            a.setRatingLabel(marketRating);
            a.setMarketImage(new javax.swing.ImageIcon( getClass().getResource("/Images/market/marketSampleImage.jpg")));
            
            Float r=Float.parseFloat(marketRating);
            if (r>8.5) {
                a.setEmojiImage(new javax.swing.ImageIcon( getClass().getResource("/Images/emoji/very-good.png")));    
        }
            else if(r>7){
                a.setEmojiImage(new javax.swing.ImageIcon( getClass().getResource("/Images/emoji/good.png")));
            
        }
            else if(r>5.5){
                a.setEmojiImage(new javax.swing.ImageIcon( getClass().getResource("/Images/emoji/neutral.png")));
            
        }
            else if(r>4.67){
                a.setEmojiImage(new javax.swing.ImageIcon( getClass().getResource("/Images/emoji/bad.png")));
            
        }
            else{
                a.setEmojiImage(new javax.swing.ImageIcon( getClass().getResource("/Images/emoji/very-bad.png")));
            
        }
            a.drawImageToPanel();
            
            marketsPlace.add(a);
            marketsPlace.setPreferredSize(new java.awt.Dimension((int)marketsPlace.getPreferredSize().getWidth(),
                    (int)marketsPlace.getPreferredSize().getHeight()+(int)Math.ceil(192/2) ));
            
            revalidate();
            repaint();


    }
    /**
     * @param args the command line arguments
     */
    private void addMarketsToScrollPane(List<List< String >> list){
        
        for (int i = 0; i < list.size(); i++) {

                addMarketToScrollPane(Integer.parseInt(list.get(i).get(0))
                        , list.get(i).get(1)
                        ,list.get(i).get(2));
                }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AppNameLabel;
    private javax.swing.JLabel AppNameLabel1;
    private javax.swing.JLabel AppNameLabel2;
    private javax.swing.JPanel CardPanel;
    private javax.swing.JLabel ErrorLabel;
    private javax.swing.JButton SignUpButton;
    private javax.swing.JButton applyLogInButton;
    private javax.swing.JButton backToMarketScreenButton;
    private javax.swing.JButton backToMarketScreenButton1;
    private javax.swing.JPanel changeSettingsPanel;
    private javax.swing.JPanel commerceWindowPanel;
    private javax.swing.JButton confirmSignUpButton1;
    private javax.swing.JTextField emailField;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPanel marketsPlace;
    private javax.swing.JScrollPane marketsScrollPane;
    private javax.swing.JPanel marketsTopPanel;
    private javax.swing.JPasswordField passwdField;
    private javax.swing.JLabel restaurantsLabel;
    private javax.swing.JPanel rootPanel;
    private javax.swing.JPanel selectedMarketPanel;
    private javax.swing.JButton settingsButton;
    private javax.swing.JTextField signUpEmailField;
    private javax.swing.JLabel signUpInformLabel;
    private javax.swing.JTextField signUpNameField1;
    private javax.swing.JPanel signUpPanel;
    private javax.swing.JPasswordField signUpPasswdField;
    private javax.swing.JTextField signUpSurNameField;
    private javax.swing.JPanel userInfoPanel;
    private javax.swing.JPanel userPanel;
    private javax.swing.JPanel userSettingsPanel;
    private javax.swing.JSplitPane windowSplitPane;
    // End of variables declaration//GEN-END:variables
}
