
import customscrollbar.customScrollBarUI;
import connectdb.ConnectDB;
import java.awt.Color;
import java.awt.Component;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ibrahim
 */
public class window extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    ConnectDB appDB;
    public window() {
        appDB=new ConnectDB();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        rootPanel = new javax.swing.JPanel();
        windowSplitPane = new javax.swing.JSplitPane();
        userPanel = new javax.swing.JPanel();
        AppNameLabel2 = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        settingsButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        cartButton = new javax.swing.JButton();
        marketButton = new javax.swing.JButton();
        CardPanel = new javax.swing.JPanel();
        commerceWindowPanel = new javax.swing.JPanel();
        marketsTopPanel = new javax.swing.JPanel();
        restaurantsLabel = new javax.swing.JLabel();
        marketsScrollPane = new javax.swing.JScrollPane();
        marketsPlace = new javax.swing.JPanel();
        loginPanel = new javax.swing.JPanel();
        emailField = new javax.swing.JTextField();
        passwdField = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        signUpInformLabel = new javax.swing.JLabel();
        SignUpButton = new javax.swing.JButton();
        AppNameLabel = new javax.swing.JLabel();
        applyLogInButton = new javax.swing.JButton();
        backToMarketScreenButton = new javax.swing.JButton();
        signUpPanel = new javax.swing.JPanel();
        signUpSurNameField = new javax.swing.JTextField();
        signUpEmailField = new javax.swing.JTextField();
        signUpPasswdField = new javax.swing.JPasswordField();
        signUpNameField1 = new javax.swing.JTextField();
        confirmSignUpButton1 = new javax.swing.JButton();
        AppNameLabel1 = new javax.swing.JLabel();
        backToMarketScreenButton1 = new javax.swing.JButton();
        ErrorLabel = new javax.swing.JLabel();
        userSettingsPanel = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        userInfoPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        htmlEditorPane = new javax.swing.JEditorPane();
        changeSettingsPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        changeSettingsCityComboBox = new javax.swing.JComboBox<>();
        changeSettingsCityLabel = new javax.swing.JLabel();
        changeSettingsAddressLabel = new javax.swing.JLabel();
        changeSettingsAddressField = new javax.swing.JTextField();
        changeSettingsPhoneField = new javax.swing.JTextField();
        changeSettingsPhoneLabel = new javax.swing.JLabel();
        changeSettingsCardLabel = new javax.swing.JLabel();
        changeSettingsCardField = new javax.swing.JTextField();
        changeSettingsApplyButton = new javax.swing.JButton();
        selectedMarketPanel = new javax.swing.JPanel();
        cartPanel = new javax.swing.JPanel();
        orderDetailsPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ProceedToCheckoutButton = new javax.swing.JButton();
        totPriceLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        itemsPanel = new javax.swing.JPanel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Deliver2Me - food delivery app");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setSize(new java.awt.Dimension(640, 360));

        rootPanel.setPreferredSize(new java.awt.Dimension(640, 360));
        rootPanel.setLayout(new java.awt.BorderLayout());

        windowSplitPane.setPreferredSize(new java.awt.Dimension(640, 360));

        userPanel.setBackground(new java.awt.Color(255, 0, 0));
        userPanel.setPreferredSize(new java.awt.Dimension(140, 360));

        AppNameLabel2.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        AppNameLabel2.setText("Deliver2Me");

        loginButton.setBackground(new java.awt.Color(254, 254, 254));
        loginButton.setForeground(new java.awt.Color(1, 1, 1));
        loginButton.setText("Login");
        loginButton.setFocusable(false);
        loginButton.setMaximumSize(new java.awt.Dimension(80, 35));
        loginButton.setMinimumSize(new java.awt.Dimension(80, 35));
        loginButton.setPreferredSize(new java.awt.Dimension(80, 35));
        loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginButtonMouseClicked(evt);
            }
        });

        settingsButton.setBackground(new java.awt.Color(254, 254, 254));
        settingsButton.setText("Settings");
        settingsButton.setFocusable(false);
        settingsButton.setPreferredSize(new java.awt.Dimension(81, 35));
        settingsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingsButtonMouseClicked(evt);
            }
        });

        logoutButton.setVisible(false);
        logoutButton.setBackground(new java.awt.Color(254, 254, 254));
        logoutButton.setText("Log out");
        logoutButton.setFocusable(false);
        logoutButton.setMaximumSize(new java.awt.Dimension(80, 35));
        logoutButton.setMinimumSize(new java.awt.Dimension(80, 35));
        logoutButton.setPreferredSize(new java.awt.Dimension(80, 35));
        logoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutButtonMouseClicked(evt);
            }
        });

        cartButton.setBackground(new java.awt.Color(254, 254, 254));
        cartButton.setText("Cart");
        cartButton.setFocusable(false);
        cartButton.setMaximumSize(new java.awt.Dimension(80, 35));
        cartButton.setMinimumSize(new java.awt.Dimension(80, 35));
        cartButton.setPreferredSize(new java.awt.Dimension(80, 35));
        cartButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cartButtonMouseClicked(evt);
            }
        });

        marketButton.setBackground(new java.awt.Color(254, 254, 254));
        marketButton.setText("Markets");
        marketButton.setFocusable(false);
        marketButton.setMaximumSize(new java.awt.Dimension(80, 35));
        marketButton.setMinimumSize(new java.awt.Dimension(80, 35));
        marketButton.setPreferredSize(new java.awt.Dimension(80, 35));
        marketButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                marketButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout userPanelLayout = new javax.swing.GroupLayout(userPanel);
        userPanel.setLayout(userPanelLayout);
        userPanelLayout.setHorizontalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AppNameLabel2)
                    .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(marketButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cartButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logoutButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(loginButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(settingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        userPanelLayout.setVerticalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AppNameLabel2)
                .addGap(18, 18, 18)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cartButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(marketButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(settingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        windowSplitPane.setLeftComponent(userPanel);

        CardPanel.setBackground(new java.awt.Color(235, 204, 204));
        CardPanel.setPreferredSize(new java.awt.Dimension(500, 360));
        CardPanel.setLayout(new java.awt.CardLayout());

        commerceWindowPanel.setBackground(new java.awt.Color(255, 255, 255));
        commerceWindowPanel.setName("rootPanel"); // NOI18N
        commerceWindowPanel.setPreferredSize(new java.awt.Dimension(500, 360));
        commerceWindowPanel.setLayout(new java.awt.BorderLayout());

        marketsTopPanel.setBackground(new java.awt.Color(240, 240, 240));
        marketsTopPanel.setForeground(new java.awt.Color(1, 1, 1));
        marketsTopPanel.setPreferredSize(new java.awt.Dimension(500, 60));

        restaurantsLabel.setBackground(new java.awt.Color(1, 1, 1));
        restaurantsLabel.setFont(new java.awt.Font("DejaVu Serif", 2, 24)); // NOI18N

        javax.swing.GroupLayout marketsTopPanelLayout = new javax.swing.GroupLayout(marketsTopPanel);
        marketsTopPanel.setLayout(marketsTopPanelLayout);
        marketsTopPanelLayout.setHorizontalGroup(
            marketsTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(marketsTopPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(restaurantsLabel)
                .addContainerGap(482, Short.MAX_VALUE))
        );
        marketsTopPanelLayout.setVerticalGroup(
            marketsTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(marketsTopPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(restaurantsLabel)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        commerceWindowPanel.add(marketsTopPanel, java.awt.BorderLayout.NORTH);

        marketsScrollPane.setBackground(new java.awt.Color(240, 240, 240));
        marketsScrollPane.setPreferredSize(new java.awt.Dimension(500, 360));
        //marketsScrollPane.getViewport().setBackground(new java.awt.Color(255, 96, 32));
        marketsScrollPane.setVerticalScrollBar(new customscrollbar.customScrollBar());

        marketsPlace.setBackground(new java.awt.Color(254, 254, 254));
        marketsPlace.setBorder(javax.swing.BorderFactory.createTitledBorder("Markets"));
        marketsPlace.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        marketsPlace.setPreferredSize(new java.awt.Dimension(500, 360));
        marketsPlace.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 20));
        marketsScrollPane.setViewportView(marketsPlace);
        //add sample markets to panel for unauthorized users
        addMarketsToScrollPane(appDB.getRestaurantsGUI());

        commerceWindowPanel.add(marketsScrollPane, java.awt.BorderLayout.CENTER);

        CardPanel.add(commerceWindowPanel, "commerceWindowCard");

        loginPanel.setBackground(new java.awt.Color(255, 255, 255));
        loginPanel.setName("loginPanel"); // NOI18N
        loginPanel.setPreferredSize(new java.awt.Dimension(500, 360));

        emailField.setForeground(new java.awt.Color(34, 34, 34));
        emailField.setText("Enter email");
        emailField.setToolTipText("Example: halilibo@mail.com");
        emailField.setName("emailField"); // NOI18N
        emailField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFieldFocusLost(evt);
            }
        });

        passwdField.setText("Enter password");
        passwdField.setToolTipText("Example: ibo123");
        passwdField.setEchoChar((char)0);
        passwdField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwdFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwdFieldFocusLost(evt);
            }
        });

        signUpInformLabel.setText("Do not have an account?");

        SignUpButton.setBackground(new java.awt.Color(254, 254, 254));
        SignUpButton.setText("Sign up");
        SignUpButton.setFocusable(false);
        SignUpButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignUpButtonMouseClicked(evt);
            }
        });

        AppNameLabel.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        AppNameLabel.setText("Deliver2Me");

        applyLogInButton.setBackground(new java.awt.Color(254, 254, 254));
        applyLogInButton.setText("Log in");
        applyLogInButton.setFocusable(false);
        applyLogInButton.setMaximumSize(new java.awt.Dimension(74, 35));
        applyLogInButton.setMinimumSize(new java.awt.Dimension(74, 35));
        applyLogInButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                applyLogInButtonMouseClicked(evt);
            }
        });
        applyLogInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyLogInButtonActionPerformed(evt);
            }
        });

        backToMarketScreenButton.setBackground(new java.awt.Color(254, 254, 254));
        backToMarketScreenButton.setText("Back");
        backToMarketScreenButton.setToolTipText("Back to marketplaces");
        backToMarketScreenButton.setFocusable(false);
        backToMarketScreenButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backToMarketScreenButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(loginPanelLayout.createSequentialGroup()
                                .addComponent(signUpInformLabel)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(loginPanelLayout.createSequentialGroup()
                                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator1)
                                    .addComponent(AppNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(emailField)
                                    .addComponent(passwdField, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGap(156, 156, 156)
                                .addComponent(backToMarketScreenButton))))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(applyLogInButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(SignUpButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AppNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backToMarketScreenButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passwdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(applyLogInButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(signUpInformLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SignUpButton)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        CardPanel.add(loginPanel, "loginWindowCard");

        signUpPanel.setBackground(new java.awt.Color(255, 255, 255));
        signUpPanel.setPreferredSize(new java.awt.Dimension(500, 360));

        signUpSurNameField.setForeground(new java.awt.Color(34, 34, 34));
        signUpSurNameField.setText("Enter surname");
        signUpSurNameField.setToolTipText("");
        signUpSurNameField.setName("emailField"); // NOI18N
        signUpSurNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                signUpSurNameFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                signUpSurNameFieldFocusLost(evt);
            }
        });

        signUpEmailField.setForeground(new java.awt.Color(34, 34, 34));
        signUpEmailField.setText("Enter email");
        signUpEmailField.setToolTipText("Example: halo@mail.com");
        signUpEmailField.setName("emailField"); // NOI18N
        signUpEmailField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                signUpEmailFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                signUpEmailFieldFocusLost(evt);
            }
        });

        signUpPasswdField.setText("Enter password");
        signUpPasswdField.setToolTipText("Example: ibo123");
        signUpPasswdField.setEchoChar((char)0);
        signUpPasswdField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                signUpPasswdFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                signUpPasswdFieldFocusLost(evt);
            }
        });

        signUpNameField1.setForeground(new java.awt.Color(34, 34, 34));
        signUpNameField1.setText("Enter name");
        signUpNameField1.setToolTipText("");
        signUpNameField1.setName("emailField"); // NOI18N
        signUpNameField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                signUpNameField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                signUpNameField1FocusLost(evt);
            }
        });

        confirmSignUpButton1.setBackground(new java.awt.Color(254, 254, 254));
        confirmSignUpButton1.setText("Confirm and Sign up");
        confirmSignUpButton1.setFocusable(false);
        confirmSignUpButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmSignUpButton1MouseClicked(evt);
            }
        });

        AppNameLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        AppNameLabel1.setText("Deliver2Me");

        backToMarketScreenButton1.setBackground(new java.awt.Color(254, 254, 254));
        backToMarketScreenButton1.setText("Back");
        backToMarketScreenButton1.setToolTipText("Back to marketplaces");
        backToMarketScreenButton1.setFocusable(false);
        backToMarketScreenButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backToMarketScreenButton1MouseClicked(evt);
            }
        });

        ErrorLabel.setBackground(new java.awt.Color(254, 254, 254));
        ErrorLabel.setForeground(new java.awt.Color(0, 0, 0));
        ErrorLabel.setText("Do not leave any field blank!");
        ErrorLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
        ErrorLabel.setVisible(false);

        javax.swing.GroupLayout signUpPanelLayout = new javax.swing.GroupLayout(signUpPanel);
        signUpPanel.setLayout(signUpPanelLayout);
        signUpPanelLayout.setHorizontalGroup(
            signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signUpPanelLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(signUpPasswdField)
                    .addComponent(signUpEmailField)
                    .addComponent(signUpSurNameField)
                    .addComponent(signUpNameField1)
                    .addComponent(AppNameLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signUpPanelLayout.createSequentialGroup()
                        .addComponent(confirmSignUpButton1)
                        .addGap(6, 6, 6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                .addComponent(backToMarketScreenButton1)
                .addContainerGap())
            .addGroup(signUpPanelLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(ErrorLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        signUpPanelLayout.setVerticalGroup(
            signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signUpPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backToMarketScreenButton1)
                    .addComponent(AppNameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(signUpNameField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(signUpSurNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(signUpEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(signUpPasswdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ErrorLabel)
                .addGap(5, 5, 5)
                .addComponent(confirmSignUpButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CardPanel.add(signUpPanel, "signUpWindowCard");

        userSettingsPanel.setBackground(new java.awt.Color(254, 254, 254));
        userSettingsPanel.setPreferredSize(new java.awt.Dimension(500, 360));

        jTabbedPane1.setBackground(new java.awt.Color(201, 201, 201));

        jScrollPane1.setVerticalScrollBar(new customscrollbar.customScrollBar());

        htmlEditorPane.setContentType("text/html"); // NOI18N
        htmlEditorPane.setText("<html> <style> #lineBorder {   border: 2px solid powderblue; } h1{   list-style-type: none;   margin: 0;   padding: 0;   overflow: hidden;   background-color: #cacaca; }  h2{   list-style-type: none;   margin: 0;   padding: 10px 0px 10px 40px;   overflow: hidden;   background-color: #cacaca; }  ul {   list-style-type: none;   margin: 0;   padding: 10px 0px 10px 40px;   overflow: hidden;   background-color: #f0f0f0; }  </style> <body>  <h1>Settings</h1>   <h2>User</h2> <ul> <li id=LineBorder><pre>Name: %s       Phone: %s</pre></li> <li id=LineBorder><pre>Surname: %s</pre></li> <li id=LineBorder><pre>Email: %s</pre></li> </ul>   <h2>Address book</h2> <ul> <li id=LineBorder ><pre>City: %s            City Code: %s</pre></li> <li id=LineBorder><pre>%s;</pre></li> <li id=LineBorder><pre>%s;</pre></li> <li id=LineBorder><pre>%s</pre></li> </ul>   <h2>Payment</h2> <ul> <li id=LineBorder><pre>Card: %s</pre></li> </ul>   </body> </html>");
        htmlEditorPane.setToolTipText("");
        jScrollPane1.setViewportView(htmlEditorPane);

        javax.swing.GroupLayout userInfoPanelLayout = new javax.swing.GroupLayout(userInfoPanel);
        userInfoPanel.setLayout(userInfoPanelLayout);
        userInfoPanelLayout.setHorizontalGroup(
            userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
                .addContainerGap())
        );
        userInfoPanelLayout.setVerticalGroup(
            userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("tab1", userInfoPanel);

        changeSettingsPanel.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(128, 128, 128));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 100));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setText("Change Settings");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(132, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        changeSettingsPanel.add(jPanel1, java.awt.BorderLayout.NORTH);

        jScrollPane3.setPreferredSize(new java.awt.Dimension(500, 260));

        jPanel2.setPreferredSize(new java.awt.Dimension(500, 260));

        changeSettingsCityComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        changeSettingsCityLabel.setText("City");
        changeSettingsCityLabel.setToolTipText("select one from box");

        changeSettingsAddressLabel.setText("Address");

        changeSettingsAddressField.setMinimumSize(new java.awt.Dimension(95, 29));

        changeSettingsPhoneField.setPreferredSize(new java.awt.Dimension(95, 29));

        changeSettingsPhoneLabel.setText("Phone");
        changeSettingsPhoneLabel.setToolTipText("it is optional");

        changeSettingsCardLabel.setText("Debit card");
        changeSettingsCardLabel.setToolTipText("Enter card number");

        changeSettingsCardField.setPreferredSize(new java.awt.Dimension(95, 29));

        changeSettingsApplyButton.setText("Apply");
        changeSettingsApplyButton.setFocusable(false);
        changeSettingsApplyButton.setPreferredSize(new java.awt.Dimension(95, 29));
        changeSettingsApplyButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changeSettingsApplyButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(changeSettingsCityLabel)
                    .addComponent(changeSettingsAddressLabel)
                    .addComponent(changeSettingsPhoneLabel)
                    .addComponent(changeSettingsCardLabel))
                .addGap(85, 85, 85)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(changeSettingsApplyButton, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(changeSettingsPhoneField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(changeSettingsCardField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(changeSettingsAddressField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(changeSettingsCityComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(114, 114, 114))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(changeSettingsCityLabel)
                    .addComponent(changeSettingsCityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(changeSettingsAddressLabel)
                    .addComponent(changeSettingsAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(changeSettingsPhoneLabel)
                    .addComponent(changeSettingsPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(changeSettingsCardLabel)
                    .addComponent(changeSettingsCardField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(changeSettingsApplyButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane3.setViewportView(jPanel2);

        changeSettingsPanel.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("tab2", changeSettingsPanel);

        javax.swing.GroupLayout userSettingsPanelLayout = new javax.swing.GroupLayout(userSettingsPanel);
        userSettingsPanel.setLayout(userSettingsPanelLayout);
        userSettingsPanelLayout.setHorizontalGroup(
            userSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        userSettingsPanelLayout.setVerticalGroup(
            userSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        CardPanel.add(userSettingsPanel, "userSettingsCard");

        selectedMarketPanel.setPreferredSize(new java.awt.Dimension(500, 360));
        selectedMarketPanel.setLayout(new java.awt.BorderLayout());
        CardPanel.add(selectedMarketPanel, "selectedMarketCard");

        cartPanel.setPreferredSize(new java.awt.Dimension(500, 360));
        cartPanel.setLayout(new java.awt.BorderLayout());

        orderDetailsPanel.setBackground(new java.awt.Color(246, 246, 246));
        orderDetailsPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 0, 0), new java.awt.Color(128, 0, 0)));
        orderDetailsPanel.setPreferredSize(new java.awt.Dimension(120, 360));

        jLabel1.setText("Subtotal");

        ProceedToCheckoutButton.setBackground(new java.awt.Color(192, 0, 0));
        ProceedToCheckoutButton.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        ProceedToCheckoutButton.setForeground(new java.awt.Color(254, 254, 254));
        ProceedToCheckoutButton.setText("Proceed");
        ProceedToCheckoutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ProceedToCheckoutButton.setFocusable(false);

        totPriceLabel.setText("jLabel2");

        javax.swing.GroupLayout orderDetailsPanelLayout = new javax.swing.GroupLayout(orderDetailsPanel);
        orderDetailsPanel.setLayout(orderDetailsPanelLayout);
        orderDetailsPanelLayout.setHorizontalGroup(
            orderDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(orderDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(ProceedToCheckoutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(totPriceLabel)
                    .addComponent(jSeparator2))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        orderDetailsPanelLayout.setVerticalGroup(
            orderDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(totPriceLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ProceedToCheckoutButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cartPanel.add(orderDetailsPanel, java.awt.BorderLayout.EAST);

        jScrollPane2.setPreferredSize(new java.awt.Dimension(380, 360));

        itemsPanel.setBackground(new java.awt.Color(246, 246, 246));
        itemsPanel.setPreferredSize(new java.awt.Dimension(380, 360));
        itemsPanel.setLayout(new javax.swing.BoxLayout(itemsPanel, javax.swing.BoxLayout.PAGE_AXIS));
        jScrollPane2.setViewportView(itemsPanel);

        cartPanel.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        CardPanel.add(cartPanel, "CartCard");

        windowSplitPane.setRightComponent(CardPanel);

        rootPanel.add(windowSplitPane, java.awt.BorderLayout.CENTER);

        getContentPane().add(rootPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFieldFocusGained
        // TODO add your handling code here:
        if ( emailField.getText().equals("Enter email")
                || emailField.getText().equals("email may be wrong!") ){
            emailField.setBackground(Color.white);
            emailField.setForeground(Color.black);
            
            emailField.setText("");
        }
    }//GEN-LAST:event_emailFieldFocusGained

    private void emailFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFieldFocusLost
        // TODO add your handling code here:
        if (emailField.getText().isEmpty() ) {
            emailField.setText( "Enter email" );
        }
    }//GEN-LAST:event_emailFieldFocusLost

    private void passwdFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwdFieldFocusGained
        // TODO add your handling code here:
        if (passwdField.getText().equals("Enter password")
                || passwdField.getText().equals("password may be wrong!")) {
            
            passwdField.setBackground(Color.white);
            passwdField.setForeground(Color.black);
            
            passwdField.setText("");
            passwdField.setEchoChar('*');
        }
    }//GEN-LAST:event_passwdFieldFocusGained

    private void passwdFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwdFieldFocusLost
        // TODO add your handling code here:
        if (passwdField.getText().isEmpty() ) {
            passwdField.setText( "Enter password" );
            passwdField.setEchoChar((char)0);
        }
    }//GEN-LAST:event_passwdFieldFocusLost

    private void SignUpButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUpButtonMouseClicked
        // TODO add your handling code here:
        java.awt.CardLayout c=(java.awt.CardLayout)(CardPanel.getLayout());
        c.show(CardPanel, "signUpWindowCard");
    }//GEN-LAST:event_SignUpButtonMouseClicked

    private void applyLogInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyLogInButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_applyLogInButtonActionPerformed

    private void backToMarketScreenButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backToMarketScreenButtonMouseClicked
        // TODO add your handling code here:
        java.awt.CardLayout c=(java.awt.CardLayout)(CardPanel.getLayout());
        c.show(CardPanel, "commerceWindowCard");
    }//GEN-LAST:event_backToMarketScreenButtonMouseClicked

    private void signUpSurNameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_signUpSurNameFieldFocusGained
        // TODO add your handling code here:
        if (signUpSurNameField.getText().equals("Enter surname")) {
            signUpSurNameField.setText("");
        }
    }//GEN-LAST:event_signUpSurNameFieldFocusGained

    private void signUpSurNameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_signUpSurNameFieldFocusLost
        // TODO add your handling code here:
        if (signUpSurNameField.getText().isEmpty()) {
            signUpSurNameField.setText("Enter surname");
        }
    }//GEN-LAST:event_signUpSurNameFieldFocusLost

    private void signUpEmailFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_signUpEmailFieldFocusGained
        // TODO add your handling code here:
        if (signUpEmailField.getText().equals("Enter email") ) {
            signUpEmailField.setText( "" );
        }
    }//GEN-LAST:event_signUpEmailFieldFocusGained

    private void signUpEmailFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_signUpEmailFieldFocusLost
        // TODO add your handling code here:
        if (signUpEmailField.getText().isEmpty() ) {
            signUpEmailField.setText( "Enter email" );
        }
    }//GEN-LAST:event_signUpEmailFieldFocusLost

    private void signUpPasswdFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_signUpPasswdFieldFocusGained
        // TODO add your handling code here:
        if (signUpPasswdField.getText().equals("Enter password") ) {
            signUpPasswdField.setText("");
            signUpPasswdField.setEchoChar('*');
        }
    }//GEN-LAST:event_signUpPasswdFieldFocusGained

    private void signUpPasswdFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_signUpPasswdFieldFocusLost
        // TODO add your handling code here:
        if (signUpPasswdField.getText().isEmpty() ) {
            signUpPasswdField.setText( "Enter password" );
            signUpPasswdField.setEchoChar((char)0);
        }
    }//GEN-LAST:event_signUpPasswdFieldFocusLost

    private void signUpNameField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_signUpNameField1FocusGained
        // TODO add your handling code here:
        if (signUpNameField1.getText().equals("Enter name")) {
            signUpNameField1.setText("");
        }
    }//GEN-LAST:event_signUpNameField1FocusGained

    private void signUpNameField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_signUpNameField1FocusLost
        // TODO add your handling code here:
        if (signUpNameField1.getText().isEmpty()) {
            signUpNameField1.setText("Enter name");
        }
    }//GEN-LAST:event_signUpNameField1FocusLost

    private void backToMarketScreenButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backToMarketScreenButton1MouseClicked
        // TODO add your handling code here:
        java.awt.CardLayout c=(java.awt.CardLayout)(CardPanel.getLayout());
        c.show(CardPanel, "commerceWindowCard");
    }//GEN-LAST:event_backToMarketScreenButton1MouseClicked

    private void loginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMouseClicked
        // TODO add your handling code here:
        java.awt.CardLayout c=(java.awt.CardLayout)(CardPanel.getLayout());
        c.show(CardPanel, "loginWindowCard");
    }//GEN-LAST:event_loginButtonMouseClicked

    private void applyLogInButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_applyLogInButtonMouseClicked
        // TODO add your handling code here:
        //appDB.logIn("halilibo@mail.com","ibo123");
        appDB.logIn(emailField.getText(), String.valueOf(passwdField.getPassword()) );
        
        //authentication failed
        if (appDB.isLogged()<1) {
            emailField.setBackground(Color.red);
            emailField.setForeground(Color.white);
            passwdField.setBackground(Color.red);
            passwdField.setForeground(Color.white);
            
            emailField.setText("email may be wrong!");
            passwdField.setText("password may be wrong!");
        }else{//auth success
            
            marketsPlace.removeAll();
            
            loginButton.setVisible(false);
            logoutButton.setVisible(true);
            
            java.awt.CardLayout c=(java.awt.CardLayout)(CardPanel.getLayout());
            c.show(CardPanel, "commerceWindowCard");
            
            addMarketsToScrollPane(appDB.account.getRestaurantsPopularity());
            
            restaurantsLabel.setText(String.format("Restaurants on %s",appDB.account.getID()[2] ));
            
            setUserSettingsFromHtml(1);
            //System.out.println(getClass().getResource("userInfoHtml.html"));
            /*
            Path fileName=Path.of( getClass().getResource("userInfoHtml.html") );
            String html=Files.readAllBytes();
            */
            
        }
    }//GEN-LAST:event_applyLogInButtonMouseClicked

    
    private void confirmSignUpButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmSignUpButton1MouseClicked
        // TODO add your handling code here:
        
        if (signUpNameField1.getText().equals("Enter name")
                || signUpSurNameField.getText().equals("Enter surname")
                || signUpEmailField.getText().equals("Enter email")
                || signUpPasswdField.getText().equals("Enter password")) {
            
            ErrorLabel.setVisible(true);
        }else{
            
            String query="insert into customer(name, surname, email, passwd)"
                    +" values (%s, %s, %s, %s)";
            query=String.format(query,
                    signUpNameField1.getText()
                    ,signUpSurNameField.getText()
                    ,signUpEmailField.getText()
                    ,String.valueOf(signUpPasswdField.getText()) );
            

            
            int response=appDB.updateDB(query);
            if (response<1) {//signup fail
                System.out.println("error while signing up: CODE:"+response);
            }
            else{//signup success
                java.awt.CardLayout c=(java.awt.CardLayout)(CardPanel.getLayout());
        c.show(CardPanel, "loginWindowCard");
            
            emailField.setText(signUpEmailField.getText());
            
            System.out.println("signUp SUCCESS!!\nemail:"
                    +signUpEmailField+
                    "\npassword:"+String.valueOf( signUpPasswdField.getText() ));
            }
            
            signUpEmailField.setText( "" );
            signUpNameField1.setText( "" );
            signUpSurNameField.setText( "" );
            signUpPasswdField.setText( "" );
            
            
            
            
            /*
            forward to settings to set up its informations
            */
        }
    }//GEN-LAST:event_confirmSignUpButton1MouseClicked

    private void settingsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsButtonMouseClicked
        // TODO add your handling code here:
        java.awt.CardLayout c=(java.awt.CardLayout)(CardPanel.getLayout());
        c.show(CardPanel, "userSettingsCard");
        
    }//GEN-LAST:event_settingsButtonMouseClicked
    private void setUserSettingsFromHtml(int command){
        
        String htlmlStr="";
        
        File f=new File("src/userInfoHtml.html");
        
        FileInputStream fis=null;
        try {
            fis=new FileInputStream(f);
            int r;
            while((r=fis.read())!=-1){
                htlmlStr+=(char)r;
            }
                fis.close();
                
                if (command<0) {
                    htlmlStr=String.format(htlmlStr,
                        "","","","",//name,phone,surname,email
                        "","","","","",//city,cCode,addr{1,2,3}
                        "");// debit cards
                
                htmlEditorPane.setText(htlmlStr);
                    
            
            }else{
                    
                
                List<String> c=appDB.account.getIDContents();//account contents
                

                //set address field contents
                String[] addr=c.get(7).split(",");
                for (int i = 3; i < addr.length; i++) {
                    addr[2]+=";"+addr[i];
                    addr[i]=null;
            }

                htlmlStr=String.format(htlmlStr,
                        c.get(3),c.get(6),c.get(4),c.get(2),//name,phone,surname,email
                        c.get(9),c.get(0),addr[0],addr[1],addr[2],//city,cCode,addr{1,2,3}
                        c.get(5));// debit cards
                
                htmlEditorPane.setText(htlmlStr);
            }
        } catch (IOException ex) {
            Logger.getLogger(window.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    private void logoutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseClicked
        // TODO add your handling code here:
        appDB.logOut();
        logoutButton.setVisible(false);
        loginButton.setVisible(true);
        setUserSettingsFromHtml(-1);
        restaurantsLabel.setText("Logged out");
        
    }//GEN-LAST:event_logoutButtonMouseClicked

    private void cartButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartButtonMouseClicked
        // TODO add your handling code here:
        java.awt.CardLayout c=(java.awt.CardLayout)(CardPanel.getLayout());
        c.show(CardPanel, "CartCard");
    }//GEN-LAST:event_cartButtonMouseClicked

    private void changeSettingsApplyButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeSettingsApplyButtonMouseClicked
        // TODO add your handling code here:
        if (appDB.isLogged()>0) {
            
        
            String query="update customer"
                    + " set city_id=%s"
                    + " address=\'%s\'";
            
            if (changeSettingsCityComboBox.getSelectedItem().toString().isEmpty()
                    || changeSettingsAddressField.getText().isEmpty()) {
                System.out.println("user have to enter at least city and address to uodate settings!");
                return;
            }
            
            query=String.format(query,
                    changeSettingsCityComboBox.getSelectedItem().toString()
                    ,changeSettingsAddressField.getText());

            if (!changeSettingsPhoneField.getText().isEmpty()) {
                query+=" phone_num=\'" +changeSettingsPhoneField.getText()+ "\'";
            }
            if (!changeSettingsCardField.getText().isEmpty()) {
                query+=" creadit_num=\'" +changeSettingsCardField.getText()+ "\'";
            }
            query+=" where email=\'"+appDB.account.getEmail()+"\'";
            System.exit(0);
            int response=appDB.updateDB(query);
            if (response<1) {//signup fail
                System.out.println("error while signing up: CODE:"+response);
            }else{
                System.out.println("user settings updated");
            }
        }
    }//GEN-LAST:event_changeSettingsApplyButtonMouseClicked

    private void marketButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_marketButtonMouseClicked
        // TODO add your handling code here:
        java.awt.CardLayout c=(java.awt.CardLayout)(CardPanel.getLayout());
            c.show(CardPanel, "commerceWindowCard");
    }//GEN-LAST:event_marketButtonMouseClicked

    public void addItemToCart(menuItemPanel p){
        itemsPanel.add(p);
    }
    public void removeItemFromCart(menuItemPanel p){
        itemsPanel.remove(p);
        revalidate();
        repaint();
    }
    
    public void getSelectedMarketPlace(marketPlaceBox market){
        
        marketDetailBox mDetail=new marketDetailBox();
        javax.swing.JPanel p=(javax.swing.JPanel)market.getComponent(0);
        javax.swing.JLabel label=(javax.swing.JLabel)p.getComponent(1);
        mDetail.setMarketNameLabel(label.getText());
        
        List<List<String>> list;
        if (appDB.isLogged()<1) {
            list=appDB.getMenues(market.getRestaurantID());
            mDetail.appendReview(appDB.getCommentsOfRestaurant(market.getRestaurantID()));
        }else{
            list=appDB.account.getMenues(market.getRestaurantID());
            mDetail.appendReview(appDB.account.getCommentsOfRestaurant(market.getRestaurantID()));
        }
        
        for (int i = 0; i < list.size(); i++) {
            mDetail.appendMenu(list.get(i).get(0), list.get(i).get(1));
        }
        
        
        selectedMarketPanel.removeAll();
        selectedMarketPanel.add(mDetail);
        
        java.awt.CardLayout c=(java.awt.CardLayout)(CardPanel.getLayout());
        c.show(CardPanel, "selectedMarketCard");
        
    }
    
    private void addMarketToScrollPane(int marketID,String marketName,String marketRating){

            marketPlaceBox a=new marketPlaceBox();
            
            a.setPreferredSize(new java.awt.Dimension(192,192));
            
            a.setRestaurantID(marketID);
            a.setNameLabel(marketName);
            a.setRatingLabel(marketRating);
            a.setMarketImage(new javax.swing.ImageIcon( getClass().getResource("/Images/market/marketSampleImage.jpg")));
            
            Float r=Float.parseFloat(marketRating);
            if (r>8.5) {
                a.setEmojiImage(new javax.swing.ImageIcon( getClass().getResource("/Images/emoji/very-good.png")));    
        }
            else if(r>7){
                a.setEmojiImage(new javax.swing.ImageIcon( getClass().getResource("/Images/emoji/good.png")));
            
        }
            else if(r>5.5){
                a.setEmojiImage(new javax.swing.ImageIcon( getClass().getResource("/Images/emoji/neutral.png")));
            
        }
            else if(r>4.67){
                a.setEmojiImage(new javax.swing.ImageIcon( getClass().getResource("/Images/emoji/bad.png")));
            
        }
            else{
                a.setEmojiImage(new javax.swing.ImageIcon( getClass().getResource("/Images/emoji/very-bad.png")));
            
        }
            a.drawImageToPanel();
            
            marketsPlace.add(a);
            marketsPlace.setPreferredSize(new java.awt.Dimension((int)marketsPlace.getPreferredSize().getWidth(),
                    (int)marketsPlace.getPreferredSize().getHeight()+(int)Math.ceil(192/2) ));
            
            revalidate();
            repaint();


    }
    /**
     * @param args the command line arguments
     */
    private void addMarketsToScrollPane(List<List< String >> list){
        
        for (int i = 0; i < list.size(); i++) {

                addMarketToScrollPane(Integer.parseInt(list.get(i).get(0))
                        , list.get(i).get(1)
                        ,list.get(i).get(2));
                }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AppNameLabel;
    private javax.swing.JLabel AppNameLabel1;
    private javax.swing.JLabel AppNameLabel2;
    private javax.swing.JPanel CardPanel;
    private javax.swing.JLabel ErrorLabel;
    private javax.swing.JButton ProceedToCheckoutButton;
    private javax.swing.JButton SignUpButton;
    private javax.swing.JButton applyLogInButton;
    private javax.swing.JButton backToMarketScreenButton;
    private javax.swing.JButton backToMarketScreenButton1;
    private javax.swing.JButton cartButton;
    private javax.swing.JPanel cartPanel;
    private javax.swing.JTextField changeSettingsAddressField;
    private javax.swing.JLabel changeSettingsAddressLabel;
    private javax.swing.JButton changeSettingsApplyButton;
    private javax.swing.JTextField changeSettingsCardField;
    private javax.swing.JLabel changeSettingsCardLabel;
    private javax.swing.JComboBox<String> changeSettingsCityComboBox;
    private javax.swing.JLabel changeSettingsCityLabel;
    private javax.swing.JPanel changeSettingsPanel;
    private javax.swing.JTextField changeSettingsPhoneField;
    private javax.swing.JLabel changeSettingsPhoneLabel;
    private javax.swing.JPanel commerceWindowPanel;
    private javax.swing.JButton confirmSignUpButton1;
    private javax.swing.JTextField emailField;
    private javax.swing.JEditorPane htmlEditorPane;
    private javax.swing.JPanel itemsPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton marketButton;
    private javax.swing.JPanel marketsPlace;
    private javax.swing.JScrollPane marketsScrollPane;
    private javax.swing.JPanel marketsTopPanel;
    private javax.swing.JPanel orderDetailsPanel;
    private javax.swing.JPasswordField passwdField;
    private javax.swing.JLabel restaurantsLabel;
    private javax.swing.JPanel rootPanel;
    private javax.swing.JPanel selectedMarketPanel;
    private javax.swing.JButton settingsButton;
    private javax.swing.JTextField signUpEmailField;
    private javax.swing.JLabel signUpInformLabel;
    private javax.swing.JTextField signUpNameField1;
    private javax.swing.JPanel signUpPanel;
    private javax.swing.JPasswordField signUpPasswdField;
    private javax.swing.JTextField signUpSurNameField;
    private javax.swing.JLabel totPriceLabel;
    private javax.swing.JPanel userInfoPanel;
    private javax.swing.JPanel userPanel;
    private javax.swing.JPanel userSettingsPanel;
    private javax.swing.JSplitPane windowSplitPane;
    // End of variables declaration//GEN-END:variables
}
